import { AIProviderError, parseListingResult, parsePropertyAnalysis, type AIProvider, type ListingGenerationInput, type PropertyAnalysisInput, type PropertyAnalysisResult, type ListingGenerationResult } from './schemas'
const NVIDIA_URL='https://integrate.api.nvidia.com/v1/chat/completions'; const DEFAULT_MODEL='nvidia/llama-3.2-nv-vision-instruct'
const VISION_PROMPT='Tu es Locat AI Vision. Observe uniquement ce qui est visible. N’invente jamais. Retourne uniquement le JSON avec detectedSpaces, visibleFeatures et uncertainElements.'
const LISTING_PROMPT='Tu es Locat AI Listing. Rédige exclusivement en français une annonce claire, professionnelle et honnête. Les données métier sont les seules sources autorisées pour le prix, la surface, le type, la localisation, le statut et le mobilier. Les observations Vision sont uniquement ce qui a été observé dans les photos. Tu peux reformuler et organiser, mais n’ajoute aucune caractéristique absente. N’estime rien, ne transforme aucune incertitude en fait. Retourne uniquement un JSON strict {"title":"...","description":"...","highlights":[],"warnings":[]} sans Markdown. Le titre doit être informatif et faire au plus 80 caractères. Les highlights doivent contenir 3 à 5 éléments réellement fournis; les incertitudes deviennent des warnings sobres.'
export class NvidiaAIProvider implements AIProvider { private apiKey=process.env.NVIDIA_API_KEY; private model=process.env.NVIDIA_MODEL||DEFAULT_MODEL
 private async complete(system:string,user:string){if(!this.apiKey)throw new AIProviderError('missing_api_key',503); const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(),45000); try{const response=await fetch(NVIDIA_URL,{method:'POST',signal:controller.signal,headers:{Authorization:`Bearer ${this.apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:this.model,temperature:0.2,max_tokens:900,messages:[{role:'system',content:system},{role:'user',content:user}]})}); if(!response.ok){const code=response.status===401?'invalid_api_key':response.status===429?'rate_limited':response.status>=500?'provider_error':'provider_error'; throw new AIProviderError(code,response.status)} const payload=await response.json(); const content=payload?.choices?.[0]?.message?.content; if(typeof content!=='string')throw new AIProviderError('invalid_output'); return content }catch(error){if(error instanceof AIProviderError)throw error; if(error instanceof DOMException&&error.name==='AbortError')throw new AIProviderError('timeout',504); throw new AIProviderError('provider_error')}finally{clearTimeout(timeout)}}
 async analyzeProperty({images}:PropertyAnalysisInput):Promise<PropertyAnalysisResult>{for(let attempt=0;attempt<3;attempt++){try{return parsePropertyAnalysis(await this.complete(VISION_PROMPT,`Analyse ces photos: ${images.slice(0,3).join('\n')}`))}catch(error){if(error instanceof AIProviderError&&error.code!=='invalid_output')throw error; if(attempt===2)throw new AIProviderError('invalid_output')}} throw new AIProviderError('invalid_output')}
 async generateListing(input:ListingGenerationInput):Promise<ListingGenerationResult>{const context=JSON.stringify(input); for(let attempt=0;attempt<3;attempt++){try{return parseListingResult(await this.complete(LISTING_PROMPT,context))}catch(error){if(error instanceof AIProviderError&&error.code!=='invalid_output')throw error; if(attempt===2)throw new AIProviderError('invalid_output')}} throw new AIProviderError('invalid_output')}
 async generateRentReminder(){throw new AIProviderError('provider_error',501)} }
